saldo1= int(input ("ingrese su saldo vencido "))
saldo2= int(input("ingrese su saldo por vencer "))
saldototal= (saldo1+saldo2)
print("Su saldo vencido es:" )
print(saldo1)
print("su saldo por vencer es:" )
print(saldo2)
print("Su saldo tolal es:")
print(saldototal)
